name: Send Proxies to Telegram

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  send:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Send to Telegram
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          #!/bin/bash
          # خواندن ۳ پروکسی اول از فایل
          PROXY1=$(head -n 1 proxy_ru.txt)
          PROXY2=$(head -n 2 proxy_ru.txt | tail -n 1)
          PROXY3=$(head -n 3 proxy_ru.txt | tail -n 1)

          # ساخت متن پیام
          MESSAGE="متصل بمانید!
          proxy 1: $PROXY1
          proxy 2: $PROXY2
          proxy 3: $PROXY3

          @KhabarNab"

          # ارسال به تلگرام
          curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
            -d "chat_id=$CHAT_ID" \
            -d "text=$MESSAGE" \
            -d "parse_mode=HTML"
